name: npm publish

on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.ref_name }}
          email: ${{ secrets.USER_EMAIL }}
          name: ${{ secrets.USER_NAME }}
      - run: |
          git config --local user.email "$email"
          git config --local user.name "$name"
          npm version $tag
          npm ci
          npm build
          npm publish
